# This workflow will verify the tests and deployment setup for a Node.js application.
# It will run on push and pull request events.

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: IPL-social    # Set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'   # Set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'             # Set this to the Node.js version to use

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm run test

      # Build application
      - name: Build application
        run: npm run build --if-present

  deploy:
    if: github.event_name == 'push' # Deploy only on push events, not pull requests
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build-and-test
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Download artifact
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      # Deploy to Azure Web App
      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
